# Don't touch me unless you know exactly what you are doing
# All of this can be edited in game using commands
# Command placeholders: {winner}

event-world: world
win-command: msg {winner} you win

spawn-location:
  world: world
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0

events:
  brackets:
    enabled: false
    spec-location:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    start-location-1:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    start-location-2:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0

  sumo:
    enabled: false
    spec-location:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    start-location-1:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    start-location-2:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0

  koth:
    enabled: false
    spec-location:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    start-location-1:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    start-location-2:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    start-location-3:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    start-location-4:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0

  lms:
    enabled: false
    spec-location:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    start-location:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0

  oitc:
    enabled: false
    spec-location:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    start-location-1:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    start-location-2:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    start-location-3:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    start-location-4:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    start-location-5:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    start-location-6:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    start-location-7:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    start-location-8:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    int-win-points: 20e

  redrover:
    enabled: false
    spec-location:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    start-location:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    blue-region: rr-blue
    red-region: rr-red

  rod:
    enabled: false
    spec-location:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    start-location:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    win-region: rod-win
    int-seconds-time-limit: 300

  spleef:
    enabled: false
    spec-location:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    start-location-1:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    start-location-2:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    snow-position-1:
      x: 0
      y: 0
      z: 0
    snow-position-2:
      x: 0
      y: 0
      z: 0

  tdm:
    enabled: false
    spec-location:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    blue-start-location:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    red-start-location:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0

  tnttag:
    enabled: false
    spec-location:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    start-location:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0

  waterdrop:
    enabled: false
    spec-location:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    start-location:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    water-position-1:
      x: 0
      y: 0
      z: 0
    water-position-2:
      x: 0
      y: 0
      z: 0
    safe-region: waterdrop-safe

  woolshuffle:
    enabled: false
    spec-location:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    start-location:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
